#!/usr/bin/python3
# SPDX-FileCopyrightText:2022 Kenta Tsukino
# SPDX-License-Identifier: BSD-Clause

import sys

args = sys.argv
if len(args)==3:
    n = int(args[1])
    m = int(args[2])
    print(n ** m)
else:
    print(-1)

